### ISSUE TITLE
Feature Request: Puppeteer options in the scraper constructor

### ISSUE THREAD

**Issue by rawnly** [OpenByteDev/SourceScraper#14]
It would be useful edit options of puppeteer in the constructor, for example `{ headless: true }` for SSR (server side) operations.

**Comment by dbelz** [comment]
Is puppeteer integrated into this package? Not really or am I wrong? Currently I'm using this to fetch the Video URL and then I use pupeteer separately to get the "real" mp4 file link

**Comment by OpenByteDev** [comment]
You can pass arguments to puppeteer with the options argument of the `Scraper.scrap` method:
```js
scraper.scrap("http://example.com", {
    runnerOptions: {
        puppeteerConfig: {
            headless: true
        }
    }
});
```

or alternatively by changing the the `Scraper.defaultOptions` property:
```js
scraper.defaultOptions = {
    runnerOptions: {
        puppeteerConfig: {
            headless: true
        }
    }
};
```

but it shouldn't be necessary to pass `headless: true` as an option as it is the default.

**Note:** You can only pass a puppeteerConfig to Scraper using puppeteer
