### ISSUE TITLE
Custom Scraper

### ISSUE THREAD

**Issue by ogoveli** [OpenByteDev/SourceScraper#16]
Hi everyone

How can i create a custom scrapper for Vidmoly or anyone does have ?

Thanks.

**Comment by OpenByteDev** [comment]
Can you post a test link for me?

**Comment by OpenByteDev** [comment]
When building a new scraper it is probably a good idea to check out the ones already implemented, this way you can learn how the API works and how other scrapers function. If the target site is using a popular player like JWPlayer or Flowplayer the `SimpleJWPlayerScraper` or the `SimpleFlowplayerScraper` could do the job.
