### ISSUE TITLE
Errors when running project

### ISSUE THREAD

**Issue by MRL-00** [OpenByteDev/SourceScraper#4]
I have added this into an Ionic project and am trying to run it however getting the below errors:

`ERROR in ./node_modules/puppeteer/lib/Launcher.js
[ng] Module not found: Error: Can't resolve 'os' in 'node_modules/puppeteer/lib'
[ng] ERROR in ./node_modules/jsdom/lib/api.js
[ng] Module not found: Error: Can't resolve 'path' in 'node_modules/jsdom/lib'
[ng] ERROR in ./node_modules/jsdom/lib/jsdom/utils.js
[ng] Module not found: Error: Can't resolve 'path' in 'node_modules/jsdom/lib/jsdom'
[ng] ERROR in ./node_modules/mime-types/index.js
[ng] Module not found: Error: Can't resolve 'path' in 'node_modules/mime-types'
[ng] ERROR in ./node_modules/puppeteer/lib/Launcher.js
[ng] Module not found: Error: Can't resolve 'path' in 'node_modules/puppeteer/lib'
[ng] ERROR in ./node_modules/puppeteer/lib/ExecutionContext.js
[ng] Module not found: Error: Can't resolve 'path' in 'node_modules/puppeteer/lib'
[ng] ERROR in ./node_modules/assert-plus/assert.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/assert-plus'
[ng] ERROR in ./node_modules/combined-stream/lib/combined_stream.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/combined-stream/lib'
[ng] ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/delayed-stream/lib'
[ng] ERROR in ./node_modules/isstream/isstream.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/isstream'
[ng] ERROR in ./node_modules/request/request.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/request'
[ng] ERROR in ./node_modules/sshpk/lib/ed-compat.js
[ng] Module not found: Error: Can't resolve 'stream' in 'node_modules/sshpk/lib'
[ng] ERROR in ./node_modules/forever-agent/index.js
[ng] Module not found: Error: Can't resolve 'tls' in 'node_modules/forever-agent'
[ng] ERROR in ./node_modules/tunnel-agent/index.js
[ng] Module not found: Error: Can't resolve 'tls' in 'node_modules/tunnel-agent'
[ng] ERROR in ./node_modules/puppeteer/lib/WebSocketTransport.js
[ng] Module not found: Error: Can't resolve 'ws' in 'node_modules/puppeteer/lib'
[ng] ERROR in ./node_modules/request/request.js
[ng] Module not found: Error: Can't resolve 'zlib' in 'node_modules/request'`

Is there something I'm missing with the install?

**Comment by OpenByteDev** [comment]
What node version are you running?
